stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "axelmr/sed-axel-lab:latest"
  DOCKER_REGISTRY: "registry.gitlab.com"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $DOCKER_REGISTRY
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  script:
    - echo "Implementa aquí el despliegue si lo necesitas (Kubernetes, SSH, etc.)"
  only:
    - main
